### ISSUE TITLE
SetVariableAtIndex not properly incrementing per use

### ISSUE THREAD

**Issue by LennardF1989** [Ludonope/BFPortalUnleashed#10]
Consider the following code:
```
let players = mod.newArrayGlobalVar();
let teamPlayers = mod.newArrayTeamVar();

players = player.AllPlayers();

teamPlayers[player.GetTeamId(1)] = players
    .filter((e) => player.GetTeamId(e) == player.GetTeamId(1));

teamPlayers[player.GetTeamId(2)] = players
    .filter((e) => player.GetTeamId(e) == player.GetTeamId(2));
```

Generates the following:
![image](https://user-images.githubusercontent.com/869973/143788705-48757330-96e1-46c5-b0ae-15b6a22898fa.png)

Shouldn't the last SetVariableAtIndex be index 1? It is now overriding the value stored in index 0.

**Comment by Ludonope** [comment]
Actually no since here I use an array to store "pseudo-variables".
Here the pseudo-variable `teamPlayers` is actually stored in `teamVar[0]`.

That mechanism allows to use an arbitrary number of pseudo-variables.

If you need to use an actual variable for some reason (such as `TrackOverTime`) you can use `mod.newTrackableTeamVar()` or the different variants.
